name: syntax_check_job
on:
 push:
  branches:
   - “githubActions_improvement”
jobs:
 syntax_check_job:
  runs-on: ubuntu-latest
  steps:
   - name: "Checkout code" 
     uses: actions/checkout@v2
   - name: "Linter execution"
     uses: github/super-linter@v3
     env:
      DEFAULT_BRANCH: “githubActions_improvement”
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LINTER_RULES_PATH: ./bingo_twingo/src/
      JAVASCRIPT_ES_CONFIG_FILE: ./bingo_twingo/.eslintrc.json
      VALIDATE_JAVASCRIPT_ES: true